/* Generated from orogen/lib/orogen/templates/tasks/Task.hpp */

#ifndef GSTREAMER_TASK_TASK_HPP
#define GSTREAMER_TASK_TASK_HPP

#include "Helpers.hpp"

#include "gst/gstelement.h"
#include "gstreamer/TaskBase.hpp"
#include "iodrivers_base/RawPacket.hpp"

#include <gst/app/gstappsink.h>
#include <gst/app/gstappsrc.h>
#include <gst/video/video-info.h>

namespace gstreamer {
    /*! \class Task
     * \brief Declare a new task context (i.e., a component)
     *
     * The corresponding C++ class can be edited in tasks/Task.hpp and
     * tasks/Task.cpp, and will be put in the gstreamer namespace.
     */
    class Task : public TaskBase {
        /** The base class is auto-generated by orogen to define the task's interface
         *
         * It is located in the .orogen/tasks folder
         */
        friend class TaskBase;

    public:
        using RawInputPort = RTT::InputPort<iodrivers_base::RawPacket>;
        using RawOutputPort = RTT::OutputPort<iodrivers_base::RawPacket>;

        template <template <typename> class Port, typename T> struct ElementPortBinding {
            ElementPortBinding(Port<T>* p, GstElement* e)
                : port{p}
                , app_element{e}
            {
            }
            Port<T>* port = nullptr;
            T memory;
            // app_element is an appsrc (appsink) for an input (output) port
            GstElement* app_element = nullptr;
        };
        using BoundRawInput =
            ElementPortBinding<RTT::InputPort, iodrivers_base::RawPacket>;
        using BoundRawOutput =
            ElementPortBinding<RTT::OutputPort, iodrivers_base::RawPacket>;

    protected:
        std::vector<BoundRawInput> m_bound_raw_in;
        std::vector<BoundRawOutput> m_bound_raw_out;
        GstElement* constructPipeline();

        std::vector<DynamicPort> configureInputs(GstElement* pipeline);
        std::vector<DynamicPort> configureOutputs(GstElement* pipeline);

        void configureRawIO(GstElement& pipeline);
        void setupRawOutputs();
        static GstFlowReturn processAppSinkNewRawSample(GstElement* appsink,
            BoundRawOutput* binding);
        void processRawInputs();
        void pushRawData(GstElement& appsrc, std::vector<std::uint8_t> const& data);
        virtual void waitForInitialData(base::Time const& deadline) override;
        virtual void processInputs() override;
        void waitFirstRawData(base::Time const& deadline);

        /*
         * Validates ports against pipeline elements and adds them (the ports) on the
         * component's dataflow interface
         *
         * Throws if a port does not have a corresponding pipeline element
         *
         * @return pair of vectors. First one has DynamicPort elements which are the
         * ports dynamically added to the component (see Commmon.hpp).
         * The second has ElementPortBinding elements, used for exchanging data between
         * the in/out ports and the pipeline
         */
        template <template <typename> class Port, typename T, bool input>
        std::pair<std::vector<DynamicPort>, std::vector<ElementPortBinding<Port, T>>>
        validatePortsWithElements(GstElement& pipeline,
            std::vector<std::string> const& port_names);

    public:
        /** TaskContext constructor for Task
         * \param name Name of the task. This name needs to be unique to make
         *             it identifiable via nameservices.
         * \param initial_state The initial TaskState of the TaskContext.
         *                      This is deprecated. It should always be the
         *                      configure state.
         */
        Task(std::string const& name = "gstreamer::Task");

        ~Task();

        /**
         * Hook called when the state machine transitions from PreOperational to
         * Stopped.
         *
         * If the code throws an exception, the transition will be aborted
         * and the component will end in the EXCEPTION state instead
         *
         * @return true if the transition can continue, false otherwise
         */
        bool configureHook();

        /**
         * Hook called when the state machine transition from Stopped to Running
         *
         * If the code throws an exception, the transition will be aborted
         * and the component will end in the EXCEPTION state instead
         *
         * @return true if the transition is successful, false otherwise
         */
        bool startHook();

        /**
         * Hook called on trigger in the Running state
         *
         * When this hook is exactly called depends on the chosen task's activity.
         * For instance, if the task context is declared as periodic in the orogen
         * specification, the task will be called at a fixed period.
         *
         * See Rock's documentation for a list of available triggering mechanisms
         *
         * The error(), exception() and fatal() calls, when called in this hook,
         * allow to get into the associated RunTimeError, Exception and
         * FatalError states.
         */
        void updateHook();

        /**
         * Hook called in the RuntimeError state, under the same conditions than
         * the updateHook
         *
         * Call recover() to go back in the Runtime state.
         */
        void errorHook();

        /**
         * Hook called when the component transitions out of the Running state
         *
         * This is called for any transition out of running, that is the
         * transitions to Stopped, Exception and Fatal
         */
        void stopHook();

        /**
         * Hook called on all transitions to PreOperational
         *
         * This is called for all transitions into PreOperational, that is
         * either from Stopped or Exception
         */
        void cleanupHook();
    };
}

#endif
